# Generated by Django 3.2.6 on 2021-08-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='attempted_solution',
            new_name='solution',
        ),
    ]
