# Generated by Django 3.2.6 on 2021-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_rename_attempted_solution_puzzle_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hints_given',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
